on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs: 
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with: 
          flutter-version: '3.7.10'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk  --debug --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphonesimulator
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/output/apk/debug/*,build/ios/iphonesimulator/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}